### ISSUE TITLE
Debian 12 (bookworm) image release

### ISSUE THREAD

**Issue by elpiel** [dtcooper/raspberrypi-os-docker#1]
Could you make a bookwork image?
It has been released on 5th of december. Not really sure if there have been previous versions with bookworm.

https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-64-bit

**Comment by dtcooper** [comment]
For you, anything! It's done. Let me know if they work okay for  you. :)

**Comment by elpiel** [comment]
Thank you very much!
I'm trying to cross compile a rust binary for the raspberry pi OS.
Sadly, libssl differs from the container that's used for the cross compilation.
Hopefully your image will solve this 😋

**Comment by dtcooper** [comment]
Good luck! This should pull all the libraries on Raspberry Pi OS's repositories, rather than Debian's.
