### ISSUE TITLE
Raspberry Pi OS Lite container

### ISSUE THREAD

**Issue by balupton** [dtcooper/raspberrypi-os-docker#2]
Seems from https://github.com/dtcooper/raspberrypi-os-docker/commit/44c79b24787d5671b085de6b78debeeec861b19d the current container is not equivalent to Lite, and that Lite support is incoming?

**Comment by dtcooper** [comment]
No, the container is not equivalent to the Lite OS image. Per the [README.md](https://github.com/dtcooper/raspberrypi-os-docker/blob/main/README.md),

> _Here are Docker container base images for building and running software that requires Raspberry Pi's Debian packageset._

Therefore, any of these containers _could_ be turned into something that matches the Raspberry Pi Lite OS image by installing the required packages. I was working on a version of the container that contained all the Lite packages pre-installed, but I never finished it. That's what you're seeing per 44c79b2, the draft of the code commented out. Does that provide more insight?

Cheers and thanks!
