### ISSUE TITLE
publish new images using cronjob?

### ISSUE THREAD

**Issue by JoarGjersund** [dtcooper/raspberrypi-os-docker#3]
Why are new images published via cronjob just building based on events (e.g. push to main should be sufficient)
Building new images regulary even if nothing has changed can have side effects if pipelines are using those images directly as it will automatically download latest image if the hash is different, causing a steady build up of images that might at some point blow the disk usage.

Removing these two lines should be sufficient:
https://github.com/dtcooper/raspberrypi-os-docker/blob/df7961e6fa0bb593adc25d058498134b590ee173/.github/workflows/build.yml#L8-L9

A workaround for this for whoever is having this issue is obviously to pin the docker image to the hash instead of the tag.

**Comment by dtcooper** [comment]
Thinking was in case of any updates to base docker images (or debian packages).

Hmmm, doesn't the caching in the workflow, prevent a new image from being uploaded if there are no changes?

https://github.com/dtcooper/raspberrypi-os-docker/blob/df7961e6fa0bb593adc25d058498134b590ee173/.github/workflows/build.yml#L98-L99

**Comment by JoarGjersund** [comment]
Oh I see. Yes it will be cached, but only if the images are referenced by the hash and not the tag, because the images all get the same tag (so image is changed, but not the tag). You can see this in the releases tab, (3,3 K untagged releases). You could for example append` ${{ github.sha }}` to the tag name, that would lock the tag to the specific release.

But I'm not sure what the convention is for this. Just adding a small warning in the README about using the hash to reference the image would be sufficient also 😁

**Comment by dtcooper** [comment]
Hmmm, I'm not 100% clear on how to solve this. Can you be more specific with what you'd like to be implemented? Happy to do the work!

**Comment by cmcclung-ANGENG** [comment]
Hey,

It looks like it's a bit of problem generally out of the box.

It seems you can use https://github.com/mag37/dockcheck

or https://github.com/containrrr/watchtower

To detect updates then act accordingly.

Another tidbit that might be useful to you is https://github.com/docker/hub-feedback/issues/403#issuecomment-1455906325 which mentions of a way to be more selective.

**Comment by nvtkaszpir** [comment]
> Why are new images published via cronjob

Frankly speaking this is a good idea, at least for base image, allowing to get a fresh base as it shows up. Doing it on Dockerfile change or git push usually is not frequent enough (depends on the repo activity).
Of course this can be a double edged sword when base image changes (like `latest` from `20.04` becomes `22.04`) so downstream image users should be aware to use pinned immutable tags or fetch image via digest (more about it below).

> ... if pipelines are using those images directly as it will automatically download latest image if the hash is different, causing a steady build up of images that might at some point blow the disk usage.

Anyone doing CI pipelines with containers should be already aware that container systems have auto garbage collection of unused/unreferenced layers (usually triggered after certain disk size capacity used, though), or they have already something like `docker system prune --yes` in the cron on the CI hosts, or even run it on ephemeral instances which fetch images from nearby pull-through caching proxies.

Some companies even do not allow using caching layers (here you could hear a long story or the paranoid security guy about container layer poisoning attack)

> moving tags
> You could for example append ${{ github.sha }} to the tag name, that would lock the tag to the specific release

There could be done a tag with appended long or short sha, but frankly speaking I believe some systems that are used for layer caching tend to update periodically the tag references (especially `latest` tag which is a special one).

True, if you want to pin the base image to the specific version you can do it in the Dockerfile directly, Example for Dockerfile.arm-v7:

```text
# https://github.com/dtcooper/raspberrypi-os-docker/pkgs/container/raspberrypi-os/237003519?tag=bookworm

ARG BASE_IMAGE=ghcr.io/dtcooper/raspberrypi-os:bookworm
ARG BASE_DIGEST=sha256:6e8bc4975d8257b44dd074b095ba289a6112c4f2222ab8ad2d690b6b9637d1ba
FROM ${BASE_IMAGE}@${BASE_DIGEST}
```

which has a benefit of allowing to use custom args for base image/digest in the pipeline if needed.

**Comment by JoarGjersund** [comment]
Great comment [nvtkaszpir](https://github.com/nvtkaszpir). I'll mark this as closed.

as a quick fix here is just and example of what I did in my github workflow to pin the image:
```
job_name:
    container:
        image: ghcr.io/dtcooper/raspberrypi-os@sha256:a481b48026f1fa84f976446a8e1fc69f80717efc1a8e88c412f0a819097a1de2
```
